spring:
  datasource:
    url: jdbc:h2:file:./target/data/testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    properties:
      org.quartz.scheduler.instanceName: QuartzDBScheduler
      org.quartz.threadPool.threadCount: 5
